### ISSUE TITLE
Great Game! A silly Question

### ISSUE THREAD

**Issue by yushangakki** [marler8997/SlimeJavascript#5]
This is a wonderful game! I have played it for so many years and whenever I play it, it reminds me of the good old days and the precious memory.

May I ask how can I run this offline? 

## Things I tried
- Try to clone the repo and run the js file using `node.js`
- Try to make it an npm package

But I still failed. Could you consider making this a reality? Thank you!

**Comment by marler8997** [comment]
You should be able to clone it and open this file `SlimeVolleyballLegacy.html` in your browser.

**Comment by yushangakki** [comment]
It works! Thank you! This is a great game!
